### PR TITLE
[TASK] Technoeconomic HERON Use-case Upload

### PR DESCRIPTION
**Pull request by sobinc1**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
#30 

##### What are the significant changes in functionality due to this change request?
microreactors-liquid-metal battery systems use-case added

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 3. Automated Tests should pass, including run_tests, pylint, and manual building tests.
- [x] 4. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test.
- [x] 5. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 6. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.

### CODE REVIEW

**Comment by PaulTalbot-INL** [comment]
It looks like some tests are failing, but not due to your request. Let me look into it.

**Comment by sobinc1** [comment]
Thanks for reviewing the request. Please let me know if you need any additional information or have any questions.

**Comment by PaulTalbot-INL** [comment]
Thank you! I'm working on figuring out why the tests aren't passing; it's not the fault of your PR. We should have it cleared up soon. Thank you for your patience. If there's any urgency to the merge, let me know!

**Comment by joshua-cogliati-inl** [comment]
Hm, it seems like this is still picking up the submodule ids from itself. It might be useful to do a `git merge origin/main` to pull in the latest changes in main.

**Review by PaulTalbot-INL — APPROVED** [review]

**Pull request merged**
