### PR TITLE
Unittest rook tester

### PR DESCRIPTION
**Pull request by caleb-sitton-inl**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
#34

##### What are the significant changes in functionality due to this change request?
This contains a file defining a new tester that inherits from `RavenPython` and simplifies the use of the `unittest` module when running unit tests through rook. The unit tests in FORCE have been updated to use this new tester.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 3. Automated Tests should pass, including run_tests, pylint, and manual building tests.
- [ ] 4. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test.
- [ ] 5. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 6. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.

### CODE REVIEW

**Comment by PaulTalbot-INL** [comment]
Do you think this might be useful more broadly to RAVEN applications, by including it in the RAVEN base testers?

**Comment by caleb-sitton-inl** [comment]
@PaulTalbot-INL Yes, I think it could be. It doesn't look like the unittest module is currently being broadly used in unit tests for RAVEN, but adding this tester would facilitate its potential use in the future in unit tests both for RAVEN and its submodules.

**Comment by PaulTalbot-INL** [comment]
@wangcj05 Here is the unit tester to look at for consideration in RAVEN instead.

**Comment by wangcj05** [comment]
[like]  Congjian Wang reacted to your message:
________________________________

**Comment by caleb-sitton-inl** [comment]
This PR has been moved to RAVEN. See [https://github.com/idaholab/raven/pull/2382](url)

**Pull request closed without merging**
